version: '2'

services:
  biserver:
    build: .
    image: zhicwu/biserver-ce${BI_IMAGE_TAG}
    hostname: ${SERVER_HOST}
    container_name: ${BI_CONTAINER_NAME}
    command: biserver
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./ext:/bi-ext:ro
      - ./data/hsqldb:/biserver-ce/data/hsqldb:rw
      - ./data/logs:/biserver-ce/tomcat/logs:rw
      - ./data/osgi/cache:/biserver-ce/pentaho-solutions/system/karaf/caches:rw
      - ./data/osgi/data:/biserver-ce/pentaho-solutions/system/karaf/data:rw
      - ./data/tmp:/tmp:rw
    environment:
      # uncomment below if you want to see the generated admin password
      #DEBUG: Y
      BI_JAVA_OPTS: '${BI_JAVA_OPTS}'
      PDI_HADOOP_CONFIG: ${PDI_HADOOP_CONFIG}
      PDI_MAX_LOG_LINES: ${PDI_MAX_LOG_LINES}
      PDI_MAX_LOG_TIMEOUT: ${PDI_MAX_LOG_TIMEOUT}
      PDI_MAX_OBJ_TIMEOUT: ${PDI_MAX_OBJ_TIMEOUT}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_EXT_PORT}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: always
